### ISSUE TITLE
Incorrect dimensons after dicom2nifti

### ISSUE THREAD

**Issue by xuesongle** [muschellij2/oro.nifti#3]

**Comment by muschellij2** [comment]
A lot of this may be due to the headers of the DICOM data.


I use `dcm2niix` from https://github.com/rordenlab/dcm2niix, which is also in https://github.com/muschellij2/dcm2niir to convert from DICOM to NIfTI.  There is also an Rcpp package called `divest` https://github.com/jonclayden/divest, which is cross-platform as well.  I'd recommend these over `dicom2nifti`.
